package com.shinkansen;

enum Station {
    TOKYO, SHINAGAWA, SHIN_YOKOHAMA,
    ODAWARA, ATAMI, MISHIMA, SHIN_FUJI, SHIZUOKA, KAKEGAWA, HAMAMATSU, TOYOHASHI,
    NAGOYA, GIFU_HASHIMA, MAIBARA, KYOTO, SHIN_OSAKA
}